config/routes.rb
Rails.application.routes.draw do
  get 'attendance/attendance'
  get 'attendance/attendance_update'
  get 'attendance/attendance_view'
  get 'attendance/holiday'
  get 'employee/add'
  #post 'employee/add'
  get 'employee/edit'
  get 'employee/details'
  get 'employee/delete'
  get 'admin/home'
  get 'employee/index'
  get 'employee/show'
  devise_for :users

  root 'admin#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employeedetail.rb
class Employeedetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  def attendance
  end

  def attendance_update
  end

  def attendance_view
  end

  def holiday
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  
  def new
    @employeedetail = Employeedetail.new
  end
  def show
    @employeedetails = Employeedetail.all
  end

  def add
    @employeedetail = Employeedetail.new(params[:employeedetail])
    if @employeedetail.save
      redirect_to employee_show_path, :notice => "Successfully created employee."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def details
    
  end

  def delete
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/admin/home.html.erb
<% if current_user %>
	<h1> Welcome </h1>
	<%= link_to 'Create Employee',  employee_index_path %><br>
	<%= link_to 'Attendance', attendance_attendance_path %>
	
<% else %>
    <h1> please login </h1>
<% end %>

app/views/attendance/attendance.html.erb
<h1>Attendance#attendance</h1>
<p>Find me in app/views/attendance/attendance.html.erb</p>

app/views/attendance/attendance_update.html.erb
<h1>Attendance#attendance_update</h1>
<p>Find me in app/views/attendance/attendance_update.html.erb</p>

app/views/attendance/attendance_view.html.erb
<h1>Attendance#attendance_view</h1>
<p>Find me in app/views/attendance/attendance_view.html.erb</p>

app/views/attendance/holiday.html.erb
<h1>Attendance#holiday</h1>
<p>Find me in app/views/attendance/holiday.html.erb</p>

app/views/employee/_form.html.erb
<%= form_for :employee do |f| %>
  
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :hire_date %><br />
    <%= f.date_select :hire_date %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/employee/add.html.erb
<%= render 'form' %>

app/views/employee/add_employee.html.erb
<%= render 'form' %>

app/views/employee/delete.html.erb
<h1>Employee#delete_employee</h1>
<p>Find me in app/views/employee/delete_employee.html.erb</p>

app/views/employee/delete_employee.html.erb
<h1>Employee#delete_employee</h1>
<p>Find me in app/views/employee/delete_employee.html.erb</p>

app/views/employee/details.html.erb
<h1>Employee#employee_details</h1>
<p>Find me in app/views/employee/employee_details.html.erb</p>

app/views/employee/edit.html.erb
<h1>Employee#edit_employee</h1>
<p>Find me in app/views/employee/edit_employee.html.erb</p>

app/views/employee/edit_employee.html.erb
<h1>Employee#edit_employee</h1>
<p>Find me in app/views/employee/edit_employee.html.erb</p>

app/views/employee/employee_details.html.erb
<h1>Employee#employee_details</h1>
<p>Find me in app/views/employee/employee_details.html.erb</p>

app/views/employee/index.html.erb
<h1>hello</h1>
<%= link_to 'Add', employee_add_path %><br>

<%= link_to 'show', employee_show_path %>

app/views/employee/show.html.erb
<h1>Employee Details</h1>
<% if current_user %>
	<% @employeedetails.each do |x| %>
		<div >
			
			<%= x.first_name %>
			<%= x.last_name %>
			<%= x.gender %>
			<%= x.hire_date %>
		</div>
	<% end %>
<% else %>
    <h1> please login </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="att/assets/stylesheet/custom.css" rel="stylesheet">

  </head>

  <body style="background: #c6c1be;">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
       
        <%= link_to "Attendence", root_url, class: "navbar-brand" %>
         
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto" >
            
            
            
          
            <% if  current_user %>
                <li  class="nav-item"> &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Log Out', destroy_user_session_path, method: :delete, confirm: "Are You Sure?" %></li>
            <% else %>
              <li class="nav-item active" >
                <%= link_to "Login", user_session_path %>
              </li>
            <% end %>
          
             
            
            
          </ul>
        </div>
      </div>
    </nav>
    <div class="container"  >
      <% flash.each do |a, b| %>
        <div class="alert alert-success">
          <%= b %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <style>
     body {

      padding-top: 70px;  
     }

     .white{
        background: white;
     }
   </style>
  </body>
</html>